### ISSUE TITLE
Error?

### ISSUE THREAD

**Issue by dumbshow** [SungjoonPark/factor_rotation#8]
Hi,

I'm able to run fr.rotate_factors on the test data without difficulty (text8_word2vec_50_5_100.csv).  However, when I try to run it on other pretained word embeddings* , I get this error after a few minutes:

```
Traceback (most recent call last):
  File "example.py", line 80, in <module>
    main()
  File "example.py", line 68, in main
    mat_L, mat_T = method_dic[method_name](unrotated)
  File "example.py", line 47, in parsimax
    return fr.rotate_factors(unrotated, 'parsimax', dtype=torch.float64, device=torch.device("cuda"))
  File "/home/ec2-user/FactorRotation/factor_rotation/_wrappers.py", line 32, in rotate_factors
    return rotate_factors(A, 'CF', dtype, device, float(k-1)/(p+k-2), 'orthogonal', **algorithm_kwargs)
  File "/home/ec2-user/FactorRotation/factor_rotation/_wrappers.py", line 49, in rotate_factors
    L, phi, T, table = gr.GPA(A, vgQ=vgQ, T=None, rotation_method=rotation_method, tol=1e-5, max_tries=30000, dtype=dtype, device=device)
  File "/home/ec2-user/FactorRotation/factor_rotation/_gpa_rotation.py", line 50, in GPA
    U, D, V = torch.svd(X)
RuntimeError: MAGMA gesdd : the updating process of SBDSDC did not converge (error: 1) at /pytorch/aten/src/THC/generic/THCTensorMathMagma.cu:378
```

Do you have idea what may be causing this?  Thank you for sharing this interesting work, and thank you in advance for any help.

* I have tried to run it on the first 800 embeddings of both of these:
https://s3.amazonaws.com/dl4j-distribution/GoogleNews-vectors-negative300.bin.gz
https://fasttext.cc/docs/en/english-vectors.html

**Comment by SungjoonPark** [comment]
Seems it's because of computing the solution of svd for a given matrix. Usually, it works well, otherwise adding a very small constant (random) noise to the input matrix of torch.svd() (such as 1e+10, like torch.svd(X +1e10) ) might help, though it is not an exact solution for those badly-conditioned input matrices. It might cause another numerical problem. I guess maybe you can try this to a different matrix(word embeddings), like first 900 or 1000 embeddings.

**Comment by dumbshow** [comment]
Thank you
